server:
  port:
    8888
spring:
  application:
    name: hireme-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/julucinho/hireme-configs
          default-label: main
          search-paths:
            - 'hireme-users*'